services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    hostname: mongo1
    command: mongod --replSet rsdota --bind_ip_all --keyFile /data/configdb/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-keyfile:/data/configdb/keyfile
      - mongo-data-1:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  mongo2:
    image: mongo:6
    container_name: mongo2
    hostname: mongo2
    command: mongod --replSet rsdota --bind_ip_all --keyFile /data/configdb/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-keyfile:/data/configdb/keyfile
      - mongo-data-2:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  mongo3:
    image: mongo:6
    container_name: mongo3
    hostname: mongo3
    command: mongod --replSet rsdota --bind_ip_all --keyFile /data/configdb/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-keyfile:/data/configdb/keyfile
      - mongo-data-3:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: >
        rabbitmqctl await_startup && rabbitmq-diagnostics -q check_port_listener 5672 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 7s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dota.API/Dockerfile
    container_name: api      
    ports:
      - "5000:5000"
    networks:
      - default
      - mongo-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - "./assets:/assets"
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  auth:
    build:
      context: .
      dockerfile: Dota.Auth/Dockerfile
    container_name: auth
    ports:
      - "5001:5001"
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongo1

  statistics:
    build:
      context: .
      dockerfile: Dota.Statistics/Dockerfile
    container_name: statistics      
    ports:
      - "5002:5002"
    networks:
      - default
      - mongo-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  front:
    build:
      context: ./front
      dockerfile: Dockerfile 
    container_name: front
    volumes:
      - "./assets:/assets"
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - NODE_ENV=production
    env_file:
      - ./front/.env.docker

volumes:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
  rabbitmq-data:

networks:
  default:
    name: dota_network
  mongo-net:
    driver: bridge