FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY Common/Dota.Common/ Common/Dota.Common/
COPY Domain/NoSql.Auth/ Domain/NoSql.Auth/
COPY Dota.Auth/ Dota.Auth/

RUN dotnet restore Dota.Auth/Dota.Auth.csproj

RUN dotnet build Dota.Auth/Dota.Auth.csproj -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app/build .

ENTRYPOINT ["dotnet", "Dota.Auth.dll"]
