services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    hostname: mongo1
    command: >
      bash -c "cp /config/keyfile /data/configdb/keyfile &&
               chmod 600 /data/configdb/keyfile &&
               exec mongod --replSet rsdota --bind_ip_all --keyFile /data/configdb/keyfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-keyfile:/config/keyfile:ro
      - mongo-data-1:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  mongo2:
    image: mongo:6
    container_name: mongo2
    hostname: mongo2
    command: >
      bash -c "cp /config/keyfile /data/configdb/keyfile &&
               chmod 600 /data/configdb/keyfile &&
               exec mongod --replSet rsdota --bind_ip_all --keyFile /data/configdb/keyfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-keyfile:/config/keyfile:ro
      - mongo-data-2:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  mongo3:
    image: mongo:6
    container_name: mongo3
    hostname: mongo3
    command: >
      bash -c "cp /config/keyfile /data/configdb/keyfile &&
               chmod 600 /data/configdb/keyfile &&
               exec mongod --replSet rsdota --bind_ip_all --keyFile /data/configdb/keyfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-keyfile:/config/keyfile:ro
      - mongo-data-3:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: >
        mongosh --quiet --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: >
        rabbitmqctl await_startup && rabbitmq-diagnostics -q check_port_listener 5672 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 7s
      retries: 3

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_NAMES: PLAINTEXT,EXTERNAL,CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: "cb11b68f-3d19-4e65-8425-1ca83e0cfd32"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    healthcheck:
      test: opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dota.API/Dockerfile
    container_name: api      
    ports:
      - "5000:5000"
    networks:
      - default
      - mongo-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - "./assets:/assets"
    depends_on:
      kafka:
        condition: service_healthy
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  auth:
    build:
      context: .
      dockerfile: Dota.Auth/Dockerfile
    container_name: auth
    ports:
      - "5001:5001"
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongo1

  statistics:
    build:
      context: .
      dockerfile: Dota.Statistics/Dockerfile
    container_name: statistics      
    ports:
      - "5002:5002"
    networks:
      - default
      - mongo-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  generator:
    build:
      context: .
      dockerfile: Dota.Generator/Dockerfile
    container_name: generator
    volumes:
      - "./Dota.Generator/assets:/assets"    
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  front:
    build:
      context: ./front
      dockerfile: Dockerfile 
    container_name: front
    volumes:
      - "./assets:/assets"
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - NODE_ENV=production
    env_file:
      - ./front/.env.docker

volumes:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
  rabbitmq-data:
  kafka-data:

networks:
  default:
    name: dota_network
  mongo-net:
    driver: bridge