<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Dota.API</RootNamespace>
        <UserSecretsId>daa510e5-12f5-4b24-83dd-b75c65b77785</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1"/>
        <PackageReference Include="MailKit" Version="3.4.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.17"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.2"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.17"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MongoDB.Driver" Version="2.26.0"/>
        <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.2"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <PackageReference Include="RabbitMQ.Client" Version="6.8.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Dota.Common\Dota.Common.csproj"/>
        <ProjectReference Include="..\Domain\Mongo.API\Mongo.API.csproj"/>
    </ItemGroup>

    <Target Name="CopyAssets" AfterTargets="Build">
        <ItemGroup>
            <Assets Include="..\assets\**\*"/>
        </ItemGroup>
        <Message Text="Copying 'assets' into '$(OutputPath)assets'" Importance="high"/>
        <Copy SourceFiles="@(Assets)" DestinationFolder="$(OutputPath)assets\%(RecursiveDir)"/>
    </Target>

    <ItemGroup>
        <Folder Include="Hero\Services\"/>
    </ItemGroup>

</Project>
